CITIBUY = {
    "po_cols": {
        "po_title": "Title",
        "po_nbr": "PO Number",
        "release_nbr": "Release Number",
        "po_type": "PO Type",
        "vendor_id": "Vendor ID",
        "name": "Vendor",
        "status": "Status",
        "cost": "Actual Cost",
        "date": "PO Date",
        # "desc": "Description",
        # "location": "Location",
        # "buyer": "Buyer",
    },
    "vendor_cols": {
        "name": "Title",
        "vendor_id": "Vendor ID",
        "contact": "Point of Contact",
        "email": "Email",
        "phone": "Phone",
    },
    "contract_cols": {
        "contract_title": "Title",
        "po_nbr": "PO Number",
        "dollar_limit": "Dollar Limit",
        "dollar_spent": "Amount Spent",
        "start_date": "Start Date",
        "end_date": "End Date",
    },
}
