CITIBUY = {
    "po_cols": {
        "po_title": "Title",
        "po_nbr": "PO Number",
        "release_nbr": "Release Number",
        "vendor_id": "Vendor ID",
        "name": "Vendor",
        "status": "PO Status",
        "agency": "PO Agency",
        "cost": "Actual Cost",
        "date": "PO Date",
        "contract_agency": "Contract Agency",
        "dollar_limit": "Contract Dollar Limit",
        "dollar_spent": "Contract Amount Spent",
        "start_date": "Contract Start Date",
        "end_date": "Contract End Date",
    },
    "vendor_cols": {
        "name": "Title",
        "vendor_id": "Vendor ID",
        "contact": "Contact",
        "email": "Email",
        "phone": "Phone",
    },
}
