CITIBUY = {
    "invoice_cols": {
        "id": "Invoice ID",
        "po_nbr": "PO Number",
        "release_nbr": "Release Number",
        "vendor_id": "Vendor ID",
        "vendor_name": "Vendor Name",
        "invoice_nbr": "Invoice Number",
        "invoice_date": "Invoice Date",
        "amount": "Amount",
        "status": "Invoice Status",
        "modified": "Last Modified",
        "po_status": "PO Status",
        "po_date": "PO Date",
        "po_cost": "PO Cost",
        "po_type": "PO Type",
        "contract_end_date": "Contract End Date",
        "contract_dollar_limit": "Contract Dollar Limit",
        "contract_amount_spent": "Contract Amount Spent",
    },
    "receipt_cols": {
        "receipt_id": "Receipt ID",
        "po_nbr": "PO Number",
        "release_nbr": "Release Number",
        "status": "Receipt Status",
        "agency": "Agency",
        "unit": "Business Unit",
        "desc": "Description",
        "created_date": "Date Created",
        "owner": "Owner",
        "approver": "Approver",
        "proxy_approver": "Proxy Approver",
        "requested_date": "Date Requested",
    },
}
