[DEFAULT]
scopes = "https://graph.microsoft.com/.default"

[TESTING]
client_id = "test_id"
client_secret = "test_secret"
tenant_id = "12345test"
site_id = "test.sharepoint.com,12345,67890"
host_name = "test.sharepoint.com"
site_name = "testSite"
drive_id = "12345test"
