NEW_REPORT = {
    "dtypes": {
        "Execution ID": "string",
        "Location": "string",
        "Status Age (days)": "int64",
        # "Days Since Creation": "int64",
        # "Status": "string",
        "Amount": "float64",
        "Document Type": "string",
        "Name": "string",
        # "Creation Date": "datetime64",
        "Vendor ID": "string",
        "Vendor Name": "string",
        "Document Number": "string",
        "Document Date": "datetime64",
        "PO Number": "string",
        # "EA Number": "string",
        # "Note": "string",
    },
    "columns": {
        "PO Number": "PO Number",
        "Vendor ID": "Vendor ID",
        "Vendor Name": "Vendor Name",
        "Document Number": "Invoice Number",
        "Document Date": "Invoice Date",
        "Amount": "Invoice Amount",
        "Execution ID": "Execution ID (Core)",
        "Location": "Location (Core)",
        "Creation Date": "Creation Date (Core)",
        "Assigned Date (Core)": "Assigned Date (Core)",
        "Name": "DGS Name",
    },
}
